# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9880705d9d216294b519311f267de4de1871edc10ab0d0b32831665abb2118fad56f85b9e997e9e7c8cd8d92eb760c9e50a9bd0d0a7a38c67ae2a1fff6f6e4d

test:
  secret_key_base: 2caf3918ee38b18c7f0163f5c30ea5f8d09b42c755211a583de3378ff9040d1174faa7187ecc50c9f48da4925e06668e24bef1023791878a201b08835e32c7da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
